apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: feature-previews
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Feature previews
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/mikogs/feature-preview-example-argocd.git
status: {}
