apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - deployment.yaml
  - service.yaml
  # - ingress.yaml

images:
  - name: fp-app-image-placeholder
    newName: '__IMAGE_WITHOUT_TAG__'
    newTag: '__IMAGE_TAG__'
