apiVersion: v1
kind: Service
metadata:
  name: fp-app
  namespace: __APP_NAME__
  labels:
    app: fp-app
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: fp-app
