apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fp-root-app
  namespace: argocd
spec:
  destination:
    namespace: feature-previews
    server: https://kubernetes.default.svc
  project: feature-previews
  source:
    path: feature-previews/
    repoURL: https://github.com/mikogs/feature-preview-example-argocd.git
    targetRevision: add-initial-application
  syncPolicy:
    automated:
      prune: true
